# Generated by Django 4.2.9 on 2026-01-21 04:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JenisKegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jenis Kegiatan',
                'verbose_name_plural': 'Jenis Kegiatan',
                'db_table': 'jenis_kegiatan',
            },
        ),
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('tanggal', models.DateField()),
                ('jumlah_peserta', models.IntegerField(default=0)),
                ('lokasi', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis_kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kegiatan', to='dhaharan.jeniskegiatan')),
            ],
            options={
                'verbose_name': 'Kegiatan',
                'verbose_name_plural': 'Kegiatan',
                'db_table': 'kegiatan',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Pengurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('jabatan', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengurus',
                'verbose_name_plural': 'Pengurus',
                'db_table': 'pengurus',
            },
        ),
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('kategori', models.CharField(choices=[('makanan', 'Makanan'), ('minuman', 'Minuman'), ('dessert', 'Dessert'), ('snack', 'Snack')], max_length=50)),
                ('tingkat_kesulitan', models.CharField(choices=[('mudah', 'Mudah'), ('sedang', 'Sedang'), ('sulit', 'Sulit')], max_length=50)),
                ('waktu_memasak', models.IntegerField(help_text='Waktu dalam menit')),
                ('waktu_persiapan', models.IntegerField(help_text='Waktu dalam menit')),
                ('porsi', models.IntegerField()),
                ('kalori', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resep',
                'verbose_name_plural': 'Resep',
                'db_table': 'resep',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusKegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Status Kegiatan',
                'verbose_name_plural': 'Status Kegiatan',
                'db_table': 'status_kegiatan',
            },
        ),
        migrations.CreateModel(
            name='TipeTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipe Transaksi',
                'verbose_name_plural': 'Tipe Transaksi',
                'db_table': 'tipe_transaksi',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('skill', models.TextField()),
                ('motivasi', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to='dhaharan.kegiatan')),
            ],
            options={
                'verbose_name': 'Volunteer',
                'verbose_name_plural': 'Volunteer',
                'db_table': 'volunteer',
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tanggal', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipe_transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi', to='dhaharan.tipetransaksi')),
            ],
            options={
                'verbose_name': 'Transaksi',
                'verbose_name_plural': 'Transaksi',
                'db_table': 'transaksi',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='TipsResep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.IntegerField()),
                ('nama', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='dhaharan.resep')),
            ],
            options={
                'verbose_name': 'Tips Resep',
                'verbose_name_plural': 'Tips Resep',
                'db_table': 'tips_resep',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='StepsResep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.IntegerField()),
                ('nama', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='dhaharan.resep')),
            ],
            options={
                'verbose_name': 'Steps Resep',
                'verbose_name_plural': 'Steps Resep',
                'db_table': 'steps_resep',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='NutrisiResep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('nilai', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrisi', to='dhaharan.resep')),
            ],
            options={
                'verbose_name': 'Nutrisi Resep',
                'verbose_name_plural': 'Nutrisi Resep',
                'db_table': 'nutrisi_resep',
            },
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='status_kegiatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kegiatan', to='dhaharan.statuskegiatan'),
        ),
        migrations.CreateModel(
            name='FotoResep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.ImageField(upload_to='resep/')),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='dhaharan.resep')),
            ],
            options={
                'verbose_name': 'Foto Resep',
                'verbose_name_plural': 'Foto Resep',
                'db_table': 'foto_resep',
            },
        ),
        migrations.CreateModel(
            name='FotoPengurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.ImageField(upload_to='pengurus/')),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pengurus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='dhaharan.pengurus')),
            ],
            options={
                'verbose_name': 'Foto Pengurus',
                'verbose_name_plural': 'Foto Pengurus',
                'db_table': 'foto_pengurus',
            },
        ),
        migrations.CreateModel(
            name='FotoKegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.ImageField(upload_to='kegiatan/')),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto', to='dhaharan.kegiatan')),
            ],
            options={
                'verbose_name': 'Foto Kegiatan',
                'verbose_name_plural': 'Foto Kegiatan',
                'db_table': 'foto_kegiatan',
            },
        ),
        migrations.CreateModel(
            name='BahanResep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('takaran', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bahan', to='dhaharan.resep')),
            ],
            options={
                'verbose_name': 'Bahan Resep',
                'verbose_name_plural': 'Bahan Resep',
                'db_table': 'bahan_resep',
            },
        ),
    ]
