# Generated by Django 4.2.9 on 2026-01-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhaharan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoresep',
            name='file_path',
            field=models.CharField(max_length=500),
        ),
    ]
