# Generated by Django 4.2.9 on 2026-01-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhaharan', '0002_alter_fotoresep_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengurus',
            name='photo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='FotoPengurus',
        ),
    ]
